Bit 62 fetch header fix
bitprim/bitprim-blockchain pull request #8
Opened 2018-03-09 19:32 UTC by ramacarlucho

2018-03-09 20:24 UTC, dario-ramos approved these changes

2018-03-12 12:48 UTC, mdallago approved these changes

2018-03-12 14:11 UTC, hanchon approved these changes

2018-03-12 17:27 UTC, fpelliccioni requested changes

2018-03-12 17:27 UTC, fpelliccioni commented on include/bitcoin/blockchain/interface/block_chain.hpp
> +    void fetch_header_txs_size(const hash_digest& hash,
`fetch_block_header_txs_size()` should be more appropriate to be consistent with `fetch_block_header()`. Same with the callback type `header_txs_size_fetch_handler`.

2018-03-12 17:27 UTC, fpelliccioni commented on src/interface/block_chain.cpp
> +        handler(error::service_stopped, nullptr, 0, std::make_shared<hash_list>(std::vector<hash_digest>()),0);
you could use `hash_list` alias of std::vector<...>

2018-03-12 17:27 UTC, fpelliccioni commented on src/interface/block_chain.cpp
> +    const auto message = std::make_shared<const header>(block_result.header());
Please add a `TODO` for remembering encapsulate the header and the tx list in a single object. It is more efficient, only one make_shared()...

2018-03-12 18:23 UTC, merged